"""Live, repeated CourtReserve fetching for Old Mill - the successor to
the frozen capture/court_reserve_old_mill.json snapshot the adapter
currently replays.

STATUS: login mechanics are real, confirmed from a captured request. The
data-fetch call is identified but its `RequestData` parameter is an
opaque encrypted blob generated by CourtReserve's own frontend JS - not
something to hand-construct. So fetch_day() takes the more robust path:
navigate a real logged-in browser to the actual scheduler page and
capture the response it gets back, rather than building the request
ourselves. One value still needed: SCHEDULER_PAGE_URL below (see
README.md > "Capturing the login request", step 7).

CURRENT LIMITATION: because we're letting the page generate its own
request, fetch_day() currently only gets whatever day the scheduler page
defaults to (today) - it doesn't yet drive the calendar's date picker to
ask for a different day. That's a reasonable v2 (either find the date
picker's real click target, or find a URL query param that presets the
date), but today-only is still useful on its own for a same-day check.

IMPORTANT finding from the login capture: this site sits behind
Cloudflare bot protection (its cookies included cf_clearance and
__cf_bm). A plain requests.post() login is likely to get a Cloudflare
challenge page back instead of a real login - Cloudflare's JS challenge
needs an actual browser to solve it. So this uses Playwright (a real,
scriptable browser) to load the login page first (letting Cloudflare's
challenge resolve and cookies get set normally), then makes the login
API call through that same browser context so it carries the right
cookies - no fragile form-field-clicking required, since the real
frontend logs in via a JSON API call rather than a plain HTML form
submit (confirmed from the captured request's `reactsubmit: true`
header and `application/json` body).

UPDATE: the first version (context.request.post() for login, headless
Chromium) got a Cloudflare 403 even for the in-browser fetch() version -
Cloudflare's bot management was very likely fingerprinting the automated
browser itself (Playwright's navigator.webdriver flag etc), not just the
request. This version launches your real installed Chrome (channel=
"chrome") instead of Playwright's bundled Chromium, patches the most
common automation tells, and runs with a VISIBLE window by default so
that if Cloudflare shows an interactive checkbox/challenge instead of an
outright block, you can solve it yourself and the script waits for you.
This combination works reliably (confirmed against real Old Mill data).

UPDATE 2: tried real Chrome in --headless mode as a speed optimization.
Result: Cloudflare blocked the login call with a 403 even with the same
stealth patches and the same real Chrome binary - headless mode itself
has fingerprint differences from a normal window (e.g. no real GPU/
rendering surface) that this site's bot detection picks up on. Chasing
that further would mean digging into deeper headless-specific fingerprint
evasion, which has quickly diminishing returns for a personal script and
starts to resemble building anti-detection tooling rather than a booking
viewer. Conclusion: keep headless=False (a visible window) as the
supported, reliable path. The --headless flag is left in place for
reference, but isn't recommended.

Requires: pip install -r requirements.txt (adds playwright), then
one-time: playwright install chromium (used only as a fallback if your
installed Chrome can't be launched)
"""

from __future__ import annotations

import json
import os
import sys
from datetime import date

from dotenv import load_dotenv
from playwright.sync_api import sync_playwright

load_dotenv()

# Old Mill's confirmed values - kept as the defaults for running this file
# directly (`py live_session.py`). CourtReserveSession itself now takes
# org_id / scheduler_page_url as constructor args, so other CourtReserve
# clubs (Churchill, Mimico) can reuse this same class once their own
# scheduler page URL is captured the same way (see README.md).
ORG_ID = "16627"  # Old Mill

# The scheduler data call, confirmed from a capture:
#   GET https://backend.courtreserve.com/api/scheduler/member-expanded
#       ?id=16627&RequestData=<opaque>&sort=&group=&filter=&jsonData=<...>
# jsonData decodes to real, useful config (SelectedCourtIds match our 4
# real courts + the WAITLIST pseudo-court, ReservationMinInterval=60,
# MemberIds=<Taylor's Old Mill member id>, etc) - but `RequestData` is an
# opaque encrypted/signed blob, clearly generated by CourtReserve's own
# frontend JS, not a plain parameter we can construct by hand. Rather than
# guess at how it's derived (risky, and likely wrong), fetch_day() below
# lets the real scheduler page generate it naturally - we navigate a
# logged-in browser to the actual booking calendar and just capture the
# response it gets back.
SCHEDULER_API_URL_FRAGMENT = "backend.courtreserve.com/api/scheduler/member-expanded"

# Old Mill's actual booking/reservation calendar page - confirmed from
# the address bar. sId=21330 matches CustomSchedulerId from the captured
# jsonData, so this is the right scheduler.
SCHEDULER_PAGE_URL = f"https://app.courtreserve.com/Online/Reservations/Bookings/{ORG_ID}?sId=21330"


# Patches the couple of automation "tells" Cloudflare's bot management is
# known to check for (navigator.webdriver above all - Playwright sets this
# to true by default, which is a dead giveaway). Injected before any page
# script runs, via context.add_init_script.
STEALTH_INIT_SCRIPT = """
Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
Object.defineProperty(navigator, 'plugins', { get: () => [1, 2, 3, 4, 5] });
Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en'] });
window.chrome = window.chrome || { runtime: {} };
"""

CLOUDFLARE_CHALLENGE_MARKERS = ("Just a moment", "cf-challenge", "Verify you are human")


class CourtReserveSession:
    """Logs into a CourtReserve club with a real browser and reuses that
    browser's authenticated context for data fetches. Confirmed working
    for Old Mill (org_id 16627); reusable for Churchill/Mimico once their
    scheduler_page_url is captured the same way (see README.md).

    headless is False by default (a visible window) rather than the usual
    default - not just so a Cloudflare "verify you're human" checkbox can
    be solved by hand, but because a real headless run of this browser
    was tried and got blocked by Cloudflare outright (see the module
    docstring's UPDATE 2). Only pass headless=True if you're deliberately
    re-testing that."""

    def __init__(
        self,
        email_env: str,
        password_env: str,
        org_id: str = ORG_ID,
        scheduler_page_url: str | None = SCHEDULER_PAGE_URL,
        headless: bool = False,
    ):
        self.email = os.environ.get(email_env)
        self.password = os.environ.get(password_env)
        if not self.email or not self.password:
            raise RuntimeError(
                f"Set {email_env} and {password_env} in a local .env file "
                "(copy .env.example to .env and fill it in)."
            )
        self.org_id = org_id
        self.scheduler_page_url = scheduler_page_url
        self._login_page_url = f"https://app.courtreserve.com/Online/Account/LogIn/{org_id}"
        self._login_api_url = f"https://app.courtreserve.com/Online/Account/Login?id={org_id}"
        self._headless = headless
        self._playwright = None
        self._browser = None
        self._context = None

    def __enter__(self) -> "CourtReserveSession":
        self._playwright = sync_playwright().start()
        # Prefer your real, already-installed Chrome over Playwright's
        # bundled Chromium - it matches what Cloudflare expects to see
        # (same binary most real visitors use) far better than a fresh
        # automation-flagged Chromium build. Falls back to bundled
        # Chromium if Chrome isn't found (e.g. not installed at all).
        try:
            self._browser = self._playwright.chromium.launch(
                channel="chrome", headless=self._headless
            )
        except Exception:
            print("Couldn't launch your installed Chrome - falling back to "
                  "Playwright's bundled Chromium (more likely to get flagged).")
            self._browser = self._playwright.chromium.launch(headless=self._headless)

        self._context = self._browser.new_context()
        self._context.add_init_script(STEALTH_INIT_SCRIPT)
        self._login()
        return self

    def __exit__(self, *exc) -> None:
        if self._browser:
            self._browser.close()
        if self._playwright:
            self._playwright.stop()

    def _login(self) -> None:
        page = self._context.new_page()
        # Load the real login page first - this is what lets Cloudflare's
        # JS challenge run and set cf_clearance, and sets the session /
        # anti-forgery cookies the login call needs.
        page.goto(self._login_page_url, wait_until="networkidle")

        if any(marker in page.content() for marker in CLOUDFLARE_CHALLENGE_MARKERS):
            if self._headless:
                # There's no visible window to solve a challenge in - the
                # whole point of the visible-window default is that you can
                # see and click a Cloudflare checkbox. Headless can't do
                # that, so fail clearly instead of hanging on an input()
                # prompt nobody can act on.
                raise RuntimeError(
                    "Cloudflare showed a verification check, but this run is "
                    "headless (no visible browser window to solve it in). "
                    "Re-run without --headless so you can solve it yourself, "
                    "then try --headless again afterwards."
                )
            print(
                "\nCloudflare is showing a verification check in the browser "
                "window. Solve it there (checkbox, puzzle, whatever it asks), "
                "wait for the real Old Mill page to appear, then come back "
                "here and press Enter to continue.\n"
            )
            input("Press Enter once you've solved it (or if nothing appeared): ")

        # IMPORTANT: the login call runs as real JavaScript INSIDE this
        # page (via page.evaluate + the page's own fetch()), not through
        # Playwright's separate context.request API. The first version of
        # this used context.request.post() and got a Cloudflare 403 back -
        # even though it shares cookies with the page, it's a distinct
        # network path that doesn't look like real browser traffic to
        # Cloudflare's bot detection. Running fetch() inside the actual
        # page makes this indistinguishable from clicking "Login" yourself.
        result = page.evaluate(
            """
            async ({url, payload}) => {
                const res = await fetch(url, {
                    method: "POST",
                    headers: {
                        "content-type": "application/json",
                        "accept": "*/*",
                        "reactsubmit": "true",
                    },
                    credentials: "include",
                    body: JSON.stringify(payload),
                });
                const text = await res.text();
                return {status: res.status, ok: res.ok, text: text};
            }
            """,
            {
                "url": self._login_api_url,
                "payload": {
                    "IsApiCall": True,
                    "UserNameOrEmail": self.email,
                    "Password": self.password,
                },
            },
        )
        if not result["ok"]:
            raise RuntimeError(
                f"CourtReserve login failed: HTTP {result['status']} - "
                f"{result['text'][:300]}"
            )
        # TODO: once we know a real success response's shape, check it
        # here explicitly (e.g. a "Success": true field in result["text"])
        # rather than just trusting a 200 status, which some APIs return
        # even on a login failure with an error payload.
        page.close()

    def fetch_day(self, day: date) -> dict:
        """Returns today's (the scheduler page's default day) real
        availability. Kept simple/standalone for the `py live_session.py`
        CLI check below - fetch_days() is what the adapter pipeline
        actually uses to cover a whole week."""
        if not self.scheduler_page_url:
            raise NotImplementedError(
                f"No scheduler_page_url set for org_id {self.org_id} - see "
                "README.md > 'Capturing the login request', step 7."
            )
        if day != date.today():
            raise NotImplementedError(
                f"fetch_day() only supports today ({date.today().isoformat()}) "
                "- use fetch_days() for a run of consecutive days."
            )

        page = self._context.new_page()
        with page.expect_response(
            lambda r: SCHEDULER_API_URL_FRAGMENT in r.url
        ) as response_info:
            page.goto(self.scheduler_page_url, wait_until="networkidle")
        response = response_info.value
        if not response.ok:
            raise RuntimeError(f"Fetch failed: HTTP {response.status}")
        data = response.json()
        page.close()
        return data

    # The scheduler's toolbar "next day" arrow - confirmed by inspecting
    # the real element (not a guess): a <button> with this exact class
    # combination, part of Kendo UI Scheduler's standard toolbar markup
    # (the same widget family behind the /api/scheduler/member-expanded
    # data endpoint itself). aria-label is included as a second, more
    # semantic way to find the same button if CourtReserve ever changes
    # its styling classes.
    _NEXT_DAY_SELECTORS = ("button.k-nav-next", '[aria-label="Next"]')

    # Kendo UI Scheduler's standard toolbar ships "prev / today / next" as
    # a set - since .k-nav-next was confirmed real (a captured button),
    # its sibling "Today" button is a reasonable bet at the matching
    # class name, used only as a corrective fallback below (never
    # required - see fetch_days_for_scheduler).
    _TODAY_SELECTORS = ("button.k-nav-today", '[aria-label="Today"]')

    def fetch_days(self, days: list[date]) -> dict[date, dict]:
        """Convenience wrapper around fetch_days_for_scheduler() using
        this session's single self.scheduler_page_url - the common case
        (Old Mill, Mimico: one club, one scheduler)."""
        if not self.scheduler_page_url:
            raise NotImplementedError(
                f"No scheduler_page_url set for org_id {self.org_id}."
            )
        return self.fetch_days_for_scheduler(self.scheduler_page_url, days)

    def fetch_days_multi(
        self, scheduler_page_urls: list[str], days: list[date]
    ) -> dict[date, dict]:
        """For a club whose courts are split across MULTIPLE scheduler
        pages (Churchill: sId=851 for courts 1-5, sId=852 for courts
        6-10 - each is its own independent Kendo Scheduler instance with
        its own date navigation state) - fetches each scheduler in turn
        (same login, separate page loads) and merges each day's "Data"
        list together, so the result looks like one combined club-wide
        response per day, same shape fetch_days() would produce for a
        single-scheduler club.

        A day only appears in the merged result if EVERY scheduler
        reached it - if courts 1-5's calendar stalls on day 4 but courts
        6-10 kept going, day 4 (and everything after) is dropped
        entirely rather than showing a club-wide day with some courts
        silently missing."""
        per_scheduler = [
            self.fetch_days_for_scheduler(url, days) for url in scheduler_page_urls
        ]
        merged: dict[date, dict] = {}
        for day in days:
            if not all(day in d for d in per_scheduler):
                break  # once any scheduler is missing a day, stop (keeps a clean prefix)
            combined_data = []
            for d in per_scheduler:
                combined_data.extend(d[day].get("Data", []))
            merged[day] = {"Data": combined_data}
        return merged

    def fetch_days_for_scheduler(
        self, scheduler_page_url: str, days: list[date]
    ) -> dict[date, dict]:
        """Fetches several consecutive days (starting from today) from
        ONE scheduler page, reusing this session's existing login: loads
        the scheduler page once (today's default view - no clicking
        needed for that one), then clicks the real "next day" toolbar
        arrow once per additional day, capturing the fresh response
        after each click.

        Safety net: CourtReserve's actual date-selection request
        (`RequestData`) is an opaque encrypted blob we've deliberately
        never tried to hand-construct - clicking the site's own button
        sidesteps that entirely, since the *site* builds the request, we
        just captured what it sends back. But to make sure a click really
        landed on the day we think it did (not silently stuck, or moved
        by more than one day), every response's own request URL is
        decoded and its `jsonData.KendoDate` field is compared against
        the expected day - that field is what genuinely told us "Year
        2026, Month 9, Day 1" in the capture this was built from. The
        moment a click's result doesn't match what was expected (wrong
        day, no response, or the button just isn't found), fetching
        stops and whatever days were already collected are returned -
        never a guess dressed up as real data.

        `days` must be consecutive and start at date.today(); returns a
        dict covering only the prefix that was actually, verifiably
        reached (which may be every requested day, or fewer).
        """
        results: dict[date, dict] = {}
        if not days:
            return results
        days = sorted(days)
        if days[0] != date.today():
            raise ValueError("fetch_days_for_scheduler() must start from today")

        page = self._context.new_page()
        try:
            with page.expect_response(
                lambda r: SCHEDULER_API_URL_FRAGMENT in r.url
            ) as response_info:
                page.goto(scheduler_page_url, wait_until="networkidle")
        except Exception as e:
            print(f"Live fetch: couldn't load {scheduler_page_url} - {e}.")
            page.close()
            return results

        response = response_info.value
        if not response.ok:
            print(
                f"Live fetch: {scheduler_page_url} came back HTTP "
                f"{response.status} - stopping there."
            )
            page.close()
            return results

        detected = self._extract_kendo_date(response)
        if detected != days[0]:
            # This is a real, confirmed thing that happens: CourtReserve
            # can carry the "last viewed date" over from a DIFFERENT
            # scheduler page loaded earlier in this same browser session
            # (seen on Churchill: its second scheduler, courts 6-10,
            # loaded showing the exact day we'd clicked "next" all the
            # way to on the FIRST scheduler, courts 1-5, moments before -
            # not today). Try clicking "Today" once to force a reset
            # before giving up - this is skipped entirely (falls straight
            # through to the failure below) if no such button is found,
            # so it can't make things worse for a club that never needed
            # it (Old Mill, Mimico, and Churchill's first scheduler never
            # exercise this path since their initial load already
            # matches today).
            clicked_today = False
            for selector in self._TODAY_SELECTORS:
                try:
                    with page.expect_response(
                        lambda r: SCHEDULER_API_URL_FRAGMENT in r.url, timeout=8_000
                    ) as response_info:
                        page.click(selector, timeout=4_000)
                    response = response_info.value
                    clicked_today = True
                    break
                except Exception:
                    continue
            if clicked_today and response.ok:
                detected = self._extract_kendo_date(response)

            if detected != days[0]:
                print(
                    f"Live fetch: expected {scheduler_page_url}'s initial load to "
                    f"show today ({days[0].isoformat()}), but its own response "
                    f"reported {detected.isoformat() if detected else 'no readable date'} "
                    + (
                        "even after clicking 'Today' to correct it"
                        if clicked_today
                        else "(no 'Today' button found to correct it)"
                    )
                    + " - stopping there rather than guess."
                )
                page.close()
                return results
        results[days[0]] = response.json()

        for target_day in days[1:]:
            if len(results) != (target_day - days[0]).days:
                break  # a previous day didn't come through - stop rather than click blind

            clicked = False
            for selector in self._NEXT_DAY_SELECTORS:
                try:
                    with page.expect_response(
                        lambda r: SCHEDULER_API_URL_FRAGMENT in r.url, timeout=10_000
                    ) as response_info:
                        page.click(selector, timeout=5_000)
                    clicked = True
                    break
                except Exception:
                    continue
            if not clicked:
                print(
                    f"Live fetch: couldn't find/click the 'next day' button on "
                    f"{scheduler_page_url} to reach {target_day.isoformat()} - "
                    "stopping there."
                )
                break

            response = response_info.value
            if not response.ok:
                print(
                    f"Live fetch: clicking 'next' on {scheduler_page_url} got "
                    f"HTTP {response.status} - stopping there."
                )
                break
            detected = self._extract_kendo_date(response)
            if detected != target_day:
                print(
                    f"Live fetch: after clicking 'next' on {scheduler_page_url}, "
                    f"expected {target_day.isoformat()} but got "
                    f"{detected.isoformat() if detected else 'no readable date'} - "
                    "stopping there rather than guess."
                )
                break
            results[target_day] = response.json()

        page.close()
        return results

    @staticmethod
    def _extract_kendo_date(response) -> date | None:
        """Pulls the day a scheduler response actually represents, using
        the *request's own* jsonData.KendoDate field (confirmed real from
        a captured request: {"KendoDate": {"Year":2026,"Month":9,"Day":1}}
        for Sept 1) rather than trusting click-counting alone. Returns
        None if that field isn't present/parseable, which callers treat
        as "not a match" (and log, rather than silently accept)."""
        try:
            from urllib.parse import parse_qs, urlparse
            query = parse_qs(urlparse(response.url).query)
            json_data_raw = query.get("jsonData", [None])[0]
            if not json_data_raw:
                return None
            parsed = json.loads(json_data_raw)
            kd = parsed.get("KendoDate") or {}
            return date(kd["Year"], kd["Month"], kd["Day"])
        except Exception:
            return None


if __name__ == "__main__":
    # `--headless` is left in as an option, but real-headless Chrome gets
    # blocked by Cloudflare here (see UPDATE 2 above) - plain
    # `py live_session.py`, no flag, is the recommended/reliable way to
    # run this.
    headless = "--headless" in sys.argv

    with CourtReserveSession(
        "COURTRESERVE_OLD_MILL_EMAIL",
        "COURTRESERVE_OLD_MILL_PASSWORD",
        headless=headless,
    ) as sess:
        data = sess.fetch_day(date.today())
        print(data)
